from furet.migration import Migration
from furet import repository
from furet.repository import csvdb
from furet.types.decree import *

class InitData(Migration):

    def up(self):
        csvdb.insert([
            DocumentType(id=1, label='Arrêté préfectoral'),
            DocumentType(id=2, label='Arrêté municipal'),
            DocumentType(id=3, label='Consultation publique'),
        ])
        csvdb.insert([
            Department(id=1, number='01', label='Ain'),
            Department(id=2, number='02', label='Aisne'),
            Department(id=3, number='03', label='Allier'),
            Department(id=4, number='04', label='Alpes-de-Haute-Provence'),
            Department(id=5, number='05', label='Hautes-Alpes'),
            Department(id=6, number='06', label='Alpes-Maritimes'),
            Department(id=7, number='07', label='Ardèche'),
            Department(id=8, number='08', label='Ardennes'),
            Department(id=9, number='09', label='Ariège'),
            Department(id=10, number='10', label='Aube'),
            Department(id=11, number='11', label='Aude'),
            Department(id=12, number='12', label='Aveyron'),
            Department(id=13, number='13', label='Bouches-du-Rhône'),
            Department(id=14, number='14', label='Calvados'),
            Department(id=15, number='15', label='Cantal'),
            Department(id=16, number='16', label='Charente'),
            Department(id=17, number='17', label='Charente-Maritime'),
            Department(id=18, number='18', label='Cher'),
            Department(id=19, number='19', label='Corrèze'),
            Department(id=200, number='2A', label='Corse-du-Sud'),
            Department(id=201, number='2B', label='Haute-Corse'),
            Department(id=21, number='21', label="Côte-d'Or"),
            Department(id=22, number='22', label="Côtes-d'Armor"),
            Department(id=23, number='23', label='Creuse'),
            Department(id=24, number='24', label='Dordogne'),
            Department(id=25, number='25', label='Doubs'),
            Department(id=26, number='26', label='Drôme'),
            Department(id=27, number='27', label='Eure'),
            Department(id=28, number='28', label='Eure-et-Loir'),
            Department(id=29, number='29', label='Finistère'),
            Department(id=30, number='30', label='Gard'),
            Department(id=31, number='31', label='Haute-Garonne'),
            Department(id=32, number='32', label='Gers'),
            Department(id=33, number='33', label='Gironde'),
            Department(id=34, number='34', label='Hérault'),
            Department(id=35, number='35', label='Ille-et-Vilaine'),
            Department(id=36, number='36', label='Indre'),
            Department(id=37, number='37', label='Indre-et-Loire'),
            Department(id=38, number='38', label='Isère'),
            Department(id=39, number='39', label='Jura'),
            Department(id=40, number='40', label='Landes'),
            Department(id=41, number='41', label='Loir-et-Cher'),
            Department(id=42, number='42', label='Loire'),
            Department(id=43, number='43', label='Haute-Loire'),
            Department(id=44, number='44', label='Loire-Atlantique'),
            Department(id=45, number='45', label='Loiret'),
            Department(id=46, number='46', label='Lot'),
            Department(id=47, number='47', label='Lot-et-Garonne'),
            Department(id=48, number='48', label='Lozère'),
            Department(id=49, number='49', label='Maine-et-Loire'),
            Department(id=50, number='50', label='Manche'),
            Department(id=51, number='51', label='Marne'),
            Department(id=52, number='52', label='Haute-Marne'),
            Department(id=53, number='53', label='Mayenne'),
            Department(id=54, number='54', label='Meurthe-et-Moselle'),
            Department(id=55, number='55', label='Meuse'),
            Department(id=56, number='56', label='Morbihan'),
            Department(id=57, number='57', label='Moselle'),
            Department(id=58, number='58', label='Nièvre'),
            Department(id=59, number='59', label='Nord'),
            Department(id=60, number='60', label='Oise'),
            Department(id=61, number='61', label='Orne'),
            Department(id=62, number='62', label='Pas-de-Calais'),
            Department(id=63, number='63', label='Puy-de-Dôme'),
            Department(id=64, number='64', label='Pyrénées-Atlantiques'),
            Department(id=65, number='65', label='Hautes-Pyrénées'),
            Department(id=66, number='66', label='Pyrénées-Orientales'),
            Department(id=67, number='67', label='Bas-Rhin'),
            Department(id=68, number='68', label='Haut-Rhin'),
            Department(id=69, number='69', label='Rhône'),
            Department(id=70, number='70', label='Haute-Saône'),
            Department(id=71, number='71', label='Saône-et-Loire'),
            Department(id=72, number='72', label='Sarthe'),
            Department(id=73, number='73', label='Savoie'),
            Department(id=74, number='74', label='Haute-Savoie'),
            Department(id=75, number='75', label='Paris'),
            Department(id=76, number='76', label='Seine-Maritime'),
            Department(id=77, number='77', label='Seine-et-Marne'),
            Department(id=78, number='78', label='Yvelines'),
            Department(id=79, number='79', label='Deux-Sèvres'),
            Department(id=80, number='80', label='Somme'),
            Department(id=81, number='81', label='Tarn'),
            Department(id=82, number='82', label='Tarn-et-Garonne'),
            Department(id=83, number='83', label='Var'),
            Department(id=84, number='84', label='Vaucluse'),
            Department(id=85, number='85', label='Vendée'),
            Department(id=86, number='86', label='Vienne'),
            Department(id=87, number='87', label='Haute-Vienne'),
            Department(id=88, number='88', label='Vosges'),
            Department(id=89, number='89', label='Yonne'),
            Department(id=90, number='90', label='Territoire de Belfort'),
            Department(id=91, number='91', label='Essonne'),
            Department(id=92, number='92', label='Hauts-de-Seine'),
            Department(id=93, number='93', label='Seine-Saint-Denis'),
            Department(id=94, number='94', label='Val-de-Marne'),
            Department(id=95, number='95', label="Val-d'Oise"),
            Department(id=971, number='971', label='Guadeloupe'),
            Department(id=972, number='972', label='Martinique'),
            Department(id=973, number='973', label='Guyane'),
            Department(id=974, number='974', label='La Réunion'),
            Department(id=976, number='976', label='Mayotte'),
        ])
        csvdb.insert([
            Topic(id=1, label='chasse'),
            Topic(id=2, label='cynégétique'),
            Topic(id=3, label='gibier'),
            Topic(id=4, label='vénerie'),
            Topic(id=5, label='armes'),
            Topic(id=6, label='tir'),
            Topic(id=7, label='munition'),
            Topic(id=8, label='CDCFS'),
            Topic(id=9, label='SDGC'),
            Topic(id=10, label='blaireau'),
            Topic(id=11, label='déterrage'),
            Topic(id=12, label='tuberculose bovine'),
            Topic(id=13, label='loup'),
            Topic(id=14, label='ours'),
            Topic(id=15, label='lynx'),
            Topic(id=16, label='chacal'),
            Topic(id=17, label='prédation'),
            Topic(id=18, label='prédateur'),
            Topic(id=19, label='tirs de défense'),
            Topic(id=20, label='tir de prélèvement'),
            Topic(id=21, label='effarouchement'),
            Topic(id=22, label='espèce animale protégée'),
            Topic(id=23, label='louveterie'),
            Topic(id=24, label='louvetier'),
            Topic(id=25, label='piège'),
            Topic(id=26, label='piégeage'),
            Topic(id=27, label='destruction'),
            Topic(id=28, label='battue'),
            Topic(id=29, label='ESOD'),
            Topic(id=30, label="espèce susceptible d'occasionner des dégâts"),
            Topic(id=31, label='sanglier'),
            Topic(id=32, label='lapin'),
            Topic(id=33, label='pigeon'),
            Topic(id=34, label='renard'),
            Topic(id=35, label='corvidés'),
            Topic(id=36, label='fouine'),
            Topic(id=37, label='martre'),
            Topic(id=38, label='belette'),
            Topic(id=39, label='putois'),
            Topic(id=40, label='corbeau freux'),
            Topic(id=41, label='corneille noire'),
            Topic(id=42, label='pie bavarde'),
            Topic(id=43, label='geai'),
            Topic(id=44, label='étourneau'),
        ])
        csvdb.insert([
            Campaign(id=1, label='Chasse', topics=list(map(repository.getTopicById, [1, 2, 3, 4, 5, 6, 7, 8, 9]))),
            Campaign(id=2, label="Espèces protégées - grands prédateurs", topics=list(map(repository.getTopicById, [13, 14, 15, 16, 17, 18, 19, 20, 21, 22]))),
            Campaign(id=3, label='Blaireau', topics=list(map(repository.getTopicById, [10, 11, 12, 4]))),
            Campaign(id=4, label='ESOD', topics=list(map(repository.getTopicById, [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]))),
            Campaign(id=5, label='CDCFS', topics=list(map(repository.getTopicById, [8]))),
        ])
